# Generated by Django 5.0.2 on 2024-04-11 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='postlanguage',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
