# Generated by Django 5.0.2 on 2024-04-12 23:24

import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_comment_user_comment_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to=post.models.upload_image, verbose_name='image'),
        ),
    ]
