# Generated by Django 4.2.3 on 2023-12-29 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='location',
        ),
    ]
