# Generated by Django 4.2.3 on 2024-01-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_category_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_head', models.CharField(max_length=60)),
                ('title_goal', models.CharField(max_length=60)),
                ('description', models.TextField(null=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pages',
            name='image',
            field=models.ImageField(upload_to='home/'),
        ),
    ]
