# Generated by Django 5.0.2 on 2024-04-11 23:03

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_pageabout_alter_pages_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='services/')),
                ('description', models.TextField(null=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=dashboard.models.image_upload, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='informaionsite',
            name='address',
            field=models.CharField(max_length=60, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='informaionsite',
            name='compalete_project',
            field=models.IntegerField(verbose_name='compalete_project'),
        ),
        migrations.AlterField(
            model_name='informaionsite',
            name='count_custemor',
            field=models.IntegerField(verbose_name='count_custemor'),
        ),
        migrations.AlterField(
            model_name='informaionsite',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='informaionsite',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='informaionsite',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='facebook'),
        ),
        migrations.AlterField(
            model_name='informaionsite',
            name='image_footer',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='image_footer'),
        ),
        migrations.AlterField(
            model_name='informaionsite',
            name='image_icon',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='image_icon'),
        ),
        migrations.AlterField(
            model_name='informaionsite',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='instagram'),
        ),
        migrations.AlterField(
            model_name='informaionsite',
            name='maps',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='maps'),
        ),
        migrations.AlterField(
            model_name='informaionsite',
            name='name',
            field=models.CharField(default='name', max_length=60, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='informaionsite',
            name='pubilished_at',
            field=models.DateTimeField(auto_now=True, verbose_name='pubilished_at'),
        ),
        migrations.AlterField(
            model_name='informaionsite',
            name='telephone',
            field=models.IntegerField(blank=True, null=True, verbose_name='telephone'),
        ),
        migrations.AlterField(
            model_name='informaionsite',
            name='title_name',
            field=models.CharField(max_length=150, verbose_name='title_name'),
        ),
        migrations.AlterField(
            model_name='informaionsite',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='twitter'),
        ),
        migrations.AlterField(
            model_name='informaionsite',
            name='whatsapp',
            field=models.URLField(blank=True, null=True, verbose_name='whatsapp'),
        ),
    ]
