# Generated by Django 5.0.2 on 2024-04-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_services_alter_image_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='url',
            field=models.URLField(default=5),
            preserve_default=False,
        ),
    ]
