# Generated by Django 5.0.2 on 2024-04-12 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_brands_alter_services_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
