# Generated by Django 5.0.2 on 2024-04-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_translatetittle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatetittle',
            name='description',
            field=models.TextField(max_length=4000, verbose_name='description'),
        ),
    ]
