# Generated by Django 5.0.2 on 2024-04-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_translatetittle_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informaionsite',
            name='compalete_project',
        ),
        migrations.RemoveField(
            model_name='informaionsite',
            name='count_custemor',
        ),
        migrations.RemoveField(
            model_name='informaionsite',
            name='description',
        ),
        migrations.RemoveField(
            model_name='informaionsite',
            name='name',
        ),
        migrations.RemoveField(
            model_name='informaionsite',
            name='title_name',
        ),
        migrations.AddField(
            model_name='informaionsite',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='description arabic'),
        ),
        migrations.AddField(
            model_name='informaionsite',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description english'),
        ),
        migrations.AddField(
            model_name='informaionsite',
            name='name_ar',
            field=models.CharField(default='name', max_length=60, verbose_name='name arabic'),
        ),
        migrations.AddField(
            model_name='informaionsite',
            name='name_en',
            field=models.CharField(default='name', max_length=60, verbose_name='name english'),
        ),
        migrations.AlterField(
            model_name='informaionsite',
            name='image_footer',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='image icon black'),
        ),
        migrations.AlterField(
            model_name='informaionsite',
            name='image_icon',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='image icon white'),
        ),
    ]
