# Generated by Django 5.0.2 on 2024-04-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_informaionsite_compalete_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informaionsite',
            name='image_footer',
        ),
        migrations.RemoveField(
            model_name='informaionsite',
            name='image_icon',
        ),
        migrations.AddField(
            model_name='informaionsite',
            name='logo_black',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='logo icon black'),
        ),
        migrations.AddField(
            model_name='informaionsite',
            name='logo_white',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='logo white'),
        ),
    ]
