# Generated by Django 5.0.2 on 2024-04-14 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_informaionsite_image_footer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informaionsite',
            old_name='telephone',
            new_name='mobile',
        ),
    ]
