# Generated by Django 5.0.2 on 2024-04-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_rename_telephone_informaionsite_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='informaionsite',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='background image'),
        ),
    ]
